apiVersion: v1
kind: Service
metadata:
  name: devcamp2023-hehe-service
  namespace: apps
spec:
  selector:
    app: devcamp2023-hehe
  ports:
    - name: devcamp2023-hehe-port
      protocol: TCP
      port: 80
      targetPort: 8080
